name:                panda
version:             0.1.0.0
github:              "githubuser/panda"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/panda#readme>

dependencies:
- base >= 4.7 && < 5
- pandoc >= 3.1
- pandoc-types == 1.23.1
- text >= 2.0.2
- aeson >= 2
- containers >= 0.6.5
- bytestring >= 0.11.5
- template-haskell >= 2.20
- temporary == 1.3
- MonadRandom == 0.6
- mtl == 2.3.1
- data-default >= 0.7.1.1
- optparse-applicative >= 0.18.1.0
- pangu-hs == 0.1.0.0


ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -O2

library:
  source-dirs: src

executables:
  panda-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - panda

tests:
  panda-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - panda
