const style = {
  'code[class*="language-"]': {
    color: 'var(--theme-code-color)',
    textShadow: '0 1px var(--theme-text-shadow-color)',
    fontFamily: "Inconsolata, Monaco, Consolas, 'Courier New', Courier, monospace",
    direction: 'ltr',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    lineHeight: '1.5',
    MozTabSize: '4',
    OTabSize: '4',
    tabSize: '4',
    WebkitHyphens: 'none',
    MozHyphens: 'none',
    msHyphens: 'none',
    hyphens: 'none',
  },
  'pre[class*="language-"]': {
    color: 'var(--theme-code-color)',
    textShadow: '0 1px var(--theme-text-shadow-color)',
    fontFamily: "Inconsolata, Monaco, Consolas, 'Courier New', Courier, monospace",
    direction: 'ltr',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    lineHeight: '1.5',
    MozTabSize: '4',
    OTabSize: '4',
    tabSize: '4',
    WebkitHyphens: 'none',
    MozHyphens: 'none',
    msHyphens: 'none',
    hyphens: 'none',
    margin: '.5em 0',
    overflow: 'auto',
    background: 'var(--theme-background-color)',
  },
  ':not(pre) > code[class*="language-"]': { background: 'var(--theme-background-color)', },
  comment: { color: 'var(--theme-comment-color)' },
  prolog: { color: 'var(--theme-comment-color)' },
  doctype: { color: 'var(--theme-comment-color)' },
  cdata: { color: 'var(--theme-comment-color)' },
  punctuation: { color: 'var(--theme-punctuation-color)' },
  '.namespace': { opacity: '.7' },
  property: { color: 'var(--theme-property-color)' },
  keyword: { color: 'var(--theme-keyword-color)' },
  tag: { color: 'var(--theme-tag-color)' },
  'class-name': { color: 'var(--theme-class-name-color)', textDecoration: 'underline' },
  boolean: { color: 'var(--theme-boolean-color)' },
  constant: { color: 'var(--theme-constant-color)' },
  symbol: { color: 'var(--theme-symbol-color)' },
  deleted: { color: 'var(--theme-deleted-color)' },
  number: { color: 'var(--theme-number-color)' },
  selector: { color: 'var(--theme-selector-color)' },
  'attr-name': { color: 'var(--theme-attr-name-color)' },
  string: { color: 'var(--theme-string-color)' },
  char: { color: 'var(--theme-char-color)' },
  builtin: { color: 'var(--theme-builtin-color)' },
  inserted: { color: 'var(--theme-inserted-color)' },
  variable: { color: 'var(--theme-variable-color)' },
  operator: { color: 'var(--theme-operator-color)' },
  function: { color: 'var(--theme-function-color)' },
  regex: { color: 'var(--theme-regex-color)' },
  important: { color: 'var(--theme-important-color)', fontWeight: 'bold' },
  entity: { color: 'var(--theme-entity-color)', cursor: 'help' },
  url: { color: 'var(--theme-url-color)' },
  '.language-css .token.string': { color: 'var(--theme-language-css-token-string-color)' },
  '.style .token.string': { color: 'var(--theme-style-token-string-color)' },
  bold: { fontWeight: 'bold' },
  italic: { fontStyle: 'italic' },
  atrule: { color: 'var(--theme-atrule-color)' },
  'attr-value': { color: 'var(--theme-attr-value-color)' }
}

export default style;
