import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import fs from 'fs';
import { getAllPosts } from './';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const posts = await getAllPosts();

let entries = '';

for (const post of posts) {
  const fileName = `${post.id}.${post.metaData.language}.${post.metaData.ext}`;
  entries += `  '${fileName}': () => import('./_posts/${fileName}'),\n`;
}

const content = `// @ts-nocheck
// This file is automatically generated. Do not modify this file manually.

const postMap: Record<string, () => Promise<{ default: React.ComponentType }>> = {
${entries}};

export const postFiles = Object.keys(postMap);

interface PostProps {
  name: string,
}

export default async function Post({ name }: PostProps) {
  const load = postMap[name];
  if (!load) throw new Error('Post not found');
  const { default: Component } = await load();
  return <Component />;
}
`;

const outPath = join(dirname(__dirname), 'index.tsx');
const check = process.argv.includes('--check');
if (check) {
  const current = fs.existsSync(outPath) ? fs.readFileSync(outPath, 'utf8') : '';
  if (current !== content) {
    console.error('src/contents/index.tsx is stale. Run: yarn generate');
    process.exit(1);
  }
  console.log('contents map is up to date');
} else {
  fs.writeFileSync(outPath, content);
}
