import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import fs from 'fs';
import { getAllPosts, Post } from './';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// @ts-ignore
const posts = await getAllPosts();

let entries = '';

for (const post of posts) {
  const fileName = `${post.id}.${post.metaData.language}.${post.metaData.ext}`;
  entries += `  '${fileName}': dynamic(() => import('./_posts/${fileName}')),\n`;
}

const content = `// @ts-nocheck
// This file is automatically generated. Do not modify this file manually.
import dynamic from 'next/dynamic';

const postMap: Record<string, React.ComponentType> = {
${entries}};

interface PostProps {
  name: string,
}

export default function Post({ name }: PostProps) {
  const Component = postMap[name];
  if (!Component) throw new Error('Post not found');
  return <Component />;
}
`;

fs.writeFileSync(join(dirname(__dirname), 'index.tsx'), content);
