// @ts-nocheck
// This file is automatically generated. Do not modify this file manually.
import dynamic from 'next/dynamic';
const postMap: Record<string, React.ComponentType> = {
  '2020-10-03-mma.en.md': dynamic(() => import('./_posts/2020-10-03-mma.en.md')),
  '2020-10-03-mma.ja.md': dynamic(() => import('./_posts/2020-10-03-mma.ja.md')),
  '2020-10-03-mma.zh-cn.md': dynamic(() => import('./_posts/2020-10-03-mma.zh-cn.md')),
  'ackermann.zh-cn.md': dynamic(() => import('./_posts/ackermann.zh-cn.md')),
  'edsac.en.md': dynamic(() => import('./_posts/edsac.en.md')),
  'edsac.ja.md': dynamic(() => import('./_posts/edsac.ja.md')),
  'edsac.zh-cn.md': dynamic(() => import('./_posts/edsac.zh-cn.md')),
  'emacs-line-number.en.md': dynamic(() => import('./_posts/emacs-line-number.en.md')),
  'emacs-line-number.ja.md': dynamic(() => import('./_posts/emacs-line-number.ja.md')),
  'emacs-line-number.zh-cn.md': dynamic(() => import('./_posts/emacs-line-number.zh-cn.md')),
  'ext-gcd.en.md': dynamic(() => import('./_posts/ext-gcd.en.md')),
  'ext-gcd.zh-cn.md': dynamic(() => import('./_posts/ext-gcd.zh-cn.md')),
  'fem_joke_1_nvshu.en.md': dynamic(() => import('./_posts/fem_joke_1_nvshu.en.md')),
  'fem_joke_1_nvshu.ja.md': dynamic(() => import('./_posts/fem_joke_1_nvshu.ja.md')),
  'fem_joke_1_nvshu.zh-cn.md': dynamic(() => import('./_posts/fem_joke_1_nvshu.zh-cn.md')),
  'fp-lc100-001-permutation.en.md': dynamic(() => import('./_posts/fp-lc100-001-permutation.en.md')),
  'fp-lc100-001-permutation.ja.md': dynamic(() => import('./_posts/fp-lc100-001-permutation.ja.md')),
  'fp-lc100-001-permutation.zh-cn.md': dynamic(() => import('./_posts/fp-lc100-001-permutation.zh-cn.md')),
  'gmp.en.md': dynamic(() => import('./_posts/gmp.en.md')),
  'gmp.ja.md': dynamic(() => import('./_posts/gmp.ja.md')),
  'gmp.zh-cn.md': dynamic(() => import('./_posts/gmp.zh-cn.md')),
  'godel.en.md': dynamic(() => import('./_posts/godel.en.md')),
  'godel.ja.md': dynamic(() => import('./_posts/godel.ja.md')),
  'godel.zh-cn.md': dynamic(() => import('./_posts/godel.zh-cn.md')),
  'hindley-milner.en.md': dynamic(() => import('./_posts/hindley-milner.en.md')),
  'hindley-milner.ja.md': dynamic(() => import('./_posts/hindley-milner.ja.md')),
  'hindley-milner.zh-cn.md': dynamic(() => import('./_posts/hindley-milner.zh-cn.md')),
  'java-stream.en.md': dynamic(() => import('./_posts/java-stream.en.md')),
  'java-stream.ja.md': dynamic(() => import('./_posts/java-stream.ja.md')),
  'java-stream.zh-cn.md': dynamic(() => import('./_posts/java-stream.zh-cn.md')),
  'lambda-the-origin.en.md': dynamic(() => import('./_posts/lambda-the-origin.en.md')),
  'lambda-the-origin.ja.md': dynamic(() => import('./_posts/lambda-the-origin.ja.md')),
  'lambda-the-origin.zh-cn.md': dynamic(() => import('./_posts/lambda-the-origin.zh-cn.md')),
  'migrate.zh-cn.org': dynamic(() => import('./_posts/migrate.zh-cn.org')),
  'my-network-config.en.md': dynamic(() => import('./_posts/my-network-config.en.md')),
  'my-network-config.ja.md': dynamic(() => import('./_posts/my-network-config.ja.md')),
  'my-network-config.zh-cn.md': dynamic(() => import('./_posts/my-network-config.zh-cn.md')),
  'parametric-poly.en.md': dynamic(() => import('./_posts/parametric-poly.en.md')),
  'parametric-poly.ja.md': dynamic(() => import('./_posts/parametric-poly.ja.md')),
  'parametric-poly.zh-cn.md': dynamic(() => import('./_posts/parametric-poly.zh-cn.md')),
  'qin-mss-bard.en.md': dynamic(() => import('./_posts/qin-mss-bard.en.md')),
  'qin-mss-bard.ja.md': dynamic(() => import('./_posts/qin-mss-bard.ja.md')),
  'qin-mss-bard.zh-cn.md': dynamic(() => import('./_posts/qin-mss-bard.zh-cn.md')),
};

interface PostProps {
  name: string,
}

export default function Post({ name }: PostProps) {
  const Component = postMap[name];
  if (!Component) throw new Error('Post not found');
  return <Component />;
}
