// This file is automatically generated. Do not modify this file manually.
//@ts-ignore
import _20201003MmaEn from './_posts/2020-10-03-mma.en.md';
//@ts-ignore
import _20201003MmaJa from './_posts/2020-10-03-mma.ja.md';
//@ts-ignore
import _20201003MmaZhCn from './_posts/2020-10-03-mma.zh-cn.md';
//@ts-ignore
import _AckermannZhCn from './_posts/ackermann.zh-cn.md';
//@ts-ignore
import _EdsacEn from './_posts/edsac.en.md';
//@ts-ignore
import _EdsacJa from './_posts/edsac.ja.md';
//@ts-ignore
import _EdsacZhCn from './_posts/edsac.zh-cn.md';
//@ts-ignore
import _EmacsLineNumberEn from './_posts/emacs-line-number.en.md';
//@ts-ignore
import _EmacsLineNumberJa from './_posts/emacs-line-number.ja.md';
//@ts-ignore
import _EmacsLineNumberZhCn from './_posts/emacs-line-number.zh-cn.md';
//@ts-ignore
import _ExtGcdEn from './_posts/ext-gcd.en.md';
//@ts-ignore
import _ExtGcdZhCn from './_posts/ext-gcd.zh-cn.md';
//@ts-ignore
import _Fem_joke_1_nvshuEn from './_posts/fem_joke_1_nvshu.en.md';
//@ts-ignore
import _Fem_joke_1_nvshuJa from './_posts/fem_joke_1_nvshu.ja.md';
//@ts-ignore
import _Fem_joke_1_nvshuZhCn from './_posts/fem_joke_1_nvshu.zh-cn.md';
//@ts-ignore
import _FpLc100001PermutationZhCn from './_posts/fp-lc100-001-permutation.zh-cn.md';
//@ts-ignore
import _GmpEn from './_posts/gmp.en.md';
//@ts-ignore
import _GmpJa from './_posts/gmp.ja.md';
//@ts-ignore
import _GmpZhCn from './_posts/gmp.zh-cn.md';
//@ts-ignore
import _GodelEn from './_posts/godel.en.md';
//@ts-ignore
import _GodelJa from './_posts/godel.ja.md';
//@ts-ignore
import _GodelZhCn from './_posts/godel.zh-cn.md';
//@ts-ignore
import _HindleyMilnerEn from './_posts/hindley-milner.en.md';
//@ts-ignore
import _HindleyMilnerJa from './_posts/hindley-milner.ja.md';
//@ts-ignore
import _HindleyMilnerZhCn from './_posts/hindley-milner.zh-cn.md';
//@ts-ignore
import _JavaStreamEn from './_posts/java-stream.en.md';
//@ts-ignore
import _JavaStreamJa from './_posts/java-stream.ja.md';
//@ts-ignore
import _JavaStreamZhCn from './_posts/java-stream.zh-cn.md';
//@ts-ignore
import _LambdaTheOriginEn from './_posts/lambda-the-origin.en.md';
//@ts-ignore
import _LambdaTheOriginJa from './_posts/lambda-the-origin.ja.md';
//@ts-ignore
import _LambdaTheOriginZhCn from './_posts/lambda-the-origin.zh-cn.md';
//@ts-ignore
import _MigrateZhCn from './_posts/migrate.zh-cn.org';
//@ts-ignore
import _MyNetworkConfigEn from './_posts/my-network-config.en.md';
//@ts-ignore
import _MyNetworkConfigJa from './_posts/my-network-config.ja.md';
//@ts-ignore
import _MyNetworkConfigZhCn from './_posts/my-network-config.zh-cn.md';
//@ts-ignore
import _ParametricPolyEn from './_posts/parametric-poly.en.md';
//@ts-ignore
import _ParametricPolyJa from './_posts/parametric-poly.ja.md';
//@ts-ignore
import _ParametricPolyZhCn from './_posts/parametric-poly.zh-cn.md';
//@ts-ignore
import _QinMssBardEn from './_posts/qin-mss-bard.en.md';
//@ts-ignore
import _QinMssBardJa from './_posts/qin-mss-bard.ja.md';
//@ts-ignore
import _QinMssBardZhCn from './_posts/qin-mss-bard.zh-cn.md';


interface PostProps {
  name: string,
}

export default function Post({ name }: PostProps) {
if (name === '2020-10-03-mma.en.md') {
  return <_20201003MmaEn />;
}
if (name === '2020-10-03-mma.ja.md') {
  return <_20201003MmaJa />;
}
if (name === '2020-10-03-mma.zh-cn.md') {
  return <_20201003MmaZhCn />;
}
if (name === 'ackermann.zh-cn.md') {
  return <_AckermannZhCn />;
}
if (name === 'edsac.en.md') {
  return <_EdsacEn />;
}
if (name === 'edsac.ja.md') {
  return <_EdsacJa />;
}
if (name === 'edsac.zh-cn.md') {
  return <_EdsacZhCn />;
}
if (name === 'emacs-line-number.en.md') {
  return <_EmacsLineNumberEn />;
}
if (name === 'emacs-line-number.ja.md') {
  return <_EmacsLineNumberJa />;
}
if (name === 'emacs-line-number.zh-cn.md') {
  return <_EmacsLineNumberZhCn />;
}
if (name === 'ext-gcd.en.md') {
  return <_ExtGcdEn />;
}
if (name === 'ext-gcd.zh-cn.md') {
  return <_ExtGcdZhCn />;
}
if (name === 'fem_joke_1_nvshu.en.md') {
  return <_Fem_joke_1_nvshuEn />;
}
if (name === 'fem_joke_1_nvshu.ja.md') {
  return <_Fem_joke_1_nvshuJa />;
}
if (name === 'fem_joke_1_nvshu.zh-cn.md') {
  return <_Fem_joke_1_nvshuZhCn />;
}
if (name === 'fp-lc100-001-permutation.zh-cn.md') {
  return <_FpLc100001PermutationZhCn />;
}
if (name === 'gmp.en.md') {
  return <_GmpEn />;
}
if (name === 'gmp.ja.md') {
  return <_GmpJa />;
}
if (name === 'gmp.zh-cn.md') {
  return <_GmpZhCn />;
}
if (name === 'godel.en.md') {
  return <_GodelEn />;
}
if (name === 'godel.ja.md') {
  return <_GodelJa />;
}
if (name === 'godel.zh-cn.md') {
  return <_GodelZhCn />;
}
if (name === 'hindley-milner.en.md') {
  return <_HindleyMilnerEn />;
}
if (name === 'hindley-milner.ja.md') {
  return <_HindleyMilnerJa />;
}
if (name === 'hindley-milner.zh-cn.md') {
  return <_HindleyMilnerZhCn />;
}
if (name === 'java-stream.en.md') {
  return <_JavaStreamEn />;
}
if (name === 'java-stream.ja.md') {
  return <_JavaStreamJa />;
}
if (name === 'java-stream.zh-cn.md') {
  return <_JavaStreamZhCn />;
}
if (name === 'lambda-the-origin.en.md') {
  return <_LambdaTheOriginEn />;
}
if (name === 'lambda-the-origin.ja.md') {
  return <_LambdaTheOriginJa />;
}
if (name === 'lambda-the-origin.zh-cn.md') {
  return <_LambdaTheOriginZhCn />;
}
if (name === 'migrate.zh-cn.org') {
  return <_MigrateZhCn />;
}
if (name === 'my-network-config.en.md') {
  return <_MyNetworkConfigEn />;
}
if (name === 'my-network-config.ja.md') {
  return <_MyNetworkConfigJa />;
}
if (name === 'my-network-config.zh-cn.md') {
  return <_MyNetworkConfigZhCn />;
}
if (name === 'parametric-poly.en.md') {
  return <_ParametricPolyEn />;
}
if (name === 'parametric-poly.ja.md') {
  return <_ParametricPolyJa />;
}
if (name === 'parametric-poly.zh-cn.md') {
  return <_ParametricPolyZhCn />;
}
if (name === 'qin-mss-bard.en.md') {
  return <_QinMssBardEn />;
}
if (name === 'qin-mss-bard.ja.md') {
  return <_QinMssBardJa />;
}
if (name === 'qin-mss-bard.zh-cn.md') {
  return <_QinMssBardZhCn />;
}

  throw new Error('Post not found');
}
